//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T.world.Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Orders
    {
        public System.Guid id { get; set; }
        public System.Guid order_id { get; set; }
        public System.Guid product_id { get; set; }
        public Nullable<decimal> price_sold { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
