//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T.world.Shared.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_specs
    {
        public System.Guid id { get; set; }
        public System.Guid Specification_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual Specification Specification { get; set; }
    }
}
