//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T.world.server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Promotions
    {
        public System.Guid id { get; set; }
        public string title { get; set; }
        public System.Guid product_id { get; set; }
        public System.Guid promotion_id { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
