//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T.world.server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public System.Guid id { get; set; }
        public System.Guid category_id { get; set; }
        public string name { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
